services:
  app:
    build: .
    ports:
      - 3000:3000
    depends_on:
      db:
        condition: service_healthy

  db:
    container_name: medicine_database
    image: postgres:latest
    restart: on-failure
    environment:
      - PGPORT=5433
      - POSTGRES_DB=medicine
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123
    ports:
      - 5433:5433
    expose:
      - 5433
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./queries:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 10
